# Generated by Django 4.0.3 on 2023-01-17 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('trans_type', models.CharField(max_length=4)),
                ('symbol', models.CharField(max_length=10)),
                ('order_type', models.CharField(max_length=5)),
                ('quantity', models.IntegerField()),
                ('rem_quantity', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=6, max_digits=19)),
            ],
        ),
    ]
