# Generated by Django 4.0.3 on 2023-01-17 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_trade'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trade',
            old_name='rem_quantity',
            new_name='filled_qnty',
        ),
    ]
