# Generated by Django 4.0.3 on 2023-01-17 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_rem_quantity_trade_filled_qnty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='symbol',
            field=models.CharField(max_length=30),
        ),
    ]
