# Generated by Django 4.0.3 on 2023-01-17 20:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_trade_order_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reporter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Trades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opentime', models.DateTimeField()),
                ('closetime', models.DateTimeField()),
                ('symbol', models.CharField(max_length=30)),
                ('avg_buy_price', models.DecimalField(decimal_places=6, max_digits=19)),
                ('avg_sell_price', models.DecimalField(decimal_places=6, max_digits=19)),
                ('net_buy_qnty', models.IntegerField()),
            ],
        ),
        migrations.RenameModel(
            old_name='Trade',
            new_name='Executions',
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=100)),
                ('pub_date', models.DateField()),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.reporter')),
            ],
            options={
                'ordering': ['headline'],
            },
        ),
    ]
