# Generated by Django 4.0.3 on 2023-01-18 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_reporter_trades_rename_trade_executions_article'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='reporter',
        ),
    ]
