# Generated by Django 4.0.3 on 2023-01-19 11:16

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_article_reporter'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trade_Starter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade_id', models.CharField(max_length=50)),
                ('time', models.DateTimeField()),
                ('trans_type', models.CharField(max_length=4)),
                ('symbol', models.CharField(max_length=30)),
                ('order_type', models.CharField(max_length=12)),
                ('quantity', models.IntegerField(default=0)),
                ('filled_qnty', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=6, max_digits=19)),
                ('createdBy', models.DateTimeField(default=datetime.datetime(2023, 1, 19, 11, 16, 0, 872263, tzinfo=utc))),
                ('updatedBy', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='executions',
            name='createdBy',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 19, 11, 16, 0, 870263, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='executions',
            name='updatedBy',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='trades',
            name='createdBy',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 19, 11, 16, 0, 871264, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='trades',
            name='updatedBy',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='executions',
            name='filled_qnty',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='executions',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='trades',
            name='net_buy_qnty',
            field=models.IntegerField(default=0),
        ),
    ]
