# Generated by Django 4.0.3 on 2023-01-19 11:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_executions_createdby_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='executions',
            name='createdBy',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='trade_starter',
            name='createdBy',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='trades',
            name='createdBy',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
